# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.ref.outputs.ref }}
    steps:
      - name: Find PR ref
        id: ref
        run: |
          curl \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Accept: application/vnd.github.v3+json' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$( echo $GITHUB_REF | sed -E -e 's?^refs/pull/([0-9]+)/merge$?\1?' )" \
          | jq -r .head.ref \
          | sed -e 's/^/::set-output name=ref::/'
        shell: bash
  echo:
    runs-on: ubuntu-latest
    needs: get
    steps:
      - run: echo ${{ needs.get.outputs.ref }}
